/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsul.cc.lpoo.cv.gui.funcionario;

import br.edu.ifsul.cc.lpoo.cv.Controle;
import br.edu.ifsul.cc.lpoo.cv.model.Funcionario;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author marina.ferreira
 */
public class JPanelFuncionarioFormulario extends javax.swing.JPanel {

    private Controle controle;
    private JPanelFuncionario pnlFuncionario;

    private Funcionario funcionario;
    private SimpleDateFormat format;

    /**
     * Creates new form JPanelFuncionarioFormulario
     */
    public JPanelFuncionarioFormulario() {
        initComponents();
    }

    public JPanelFuncionarioFormulario(JPanelFuncionario pnlFuncionario, Controle controle) {

        this.pnlFuncionario = pnlFuncionario;
        this.controle = controle;
        initComponents();
        format = new SimpleDateFormat("dd/MM/yyyy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlSul = new javax.swing.JPanel();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jpsfSenha = new javax.swing.JPasswordField();
        lblCPF = new javax.swing.JLabel();
        txfCPF = new javax.swing.JTextField();
        lblDtCadastro = new javax.swing.JLabel();
        lblDataUltimoLogin = new javax.swing.JLabel();
        txfDataCadastro = new javax.swing.JTextField();
        txfDataNascimento = new javax.swing.JTextField();

        jPanel1.setLayout(new java.awt.BorderLayout());

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        pnlSul.add(btnGravar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlSul.add(btnCancelar);

        jPanel1.add(pnlSul, java.awt.BorderLayout.PAGE_END);

        pnlCentro.setLayout(new java.awt.GridBagLayout());

        lblNome.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(lblNome, gridBagConstraints);

        txfNome.setColumns(15);
        txfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfNome, gridBagConstraints);

        jLabel2.setText("Senha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(jLabel2, gridBagConstraints);

        jpsfSenha.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(jpsfSenha, gridBagConstraints);

        lblCPF.setText("CPF:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(lblCPF, gridBagConstraints);

        txfCPF.setColumns(5);
        txfCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCPFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfCPF, gridBagConstraints);

        lblDtCadastro.setText("Data de Cadastro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(lblDtCadastro, gridBagConstraints);

        lblDataUltimoLogin.setText("Data de Nascimento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(lblDataUltimoLogin, gridBagConstraints);

        txfDataCadastro.setEditable(false);
        txfDataCadastro.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfDataCadastro, gridBagConstraints);

        txfDataNascimento.setEditable(false);
        txfDataNascimento.setColumns(10);
        txfDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDataNascimentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfDataNascimento, gridBagConstraints);

        jPanel1.add(pnlCentro, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed

        //programação referente ao clique no botão Gravar.

        Funcionario f = getFuncionariobyFormulario();//recupera os dados do formulÃ¡rio

        if(f != null){

            try {

                pnlFuncionario.getControle().getConexaoJDBC().persist(f);

                JOptionPane.showMessageDialog(this, "Funcionario armazenado!", "Salvar", JOptionPane.INFORMATION_MESSAGE);

                pnlFuncionario.showTela("tela_funcionario_listagem");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar Funcionario! : "+ex.getMessage(), "Salvar", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }

        }else{

            JOptionPane.showMessageDialog(this, "Preencha o formulário!", "Edição", JOptionPane.INFORMATION_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        //programação referente ao clique no botão Cancelar.
        pnlFuncionario.showTela("tela_funcionario_listagem");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txfCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCPFActionPerformed

    private void txfDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDataNascimentoActionPerformed

    private void txfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNomeActionPerformed
    
    public Funcionario getFuncionariobyFormulario(){
        
        //validacao do formulario
         if(txfNome.getText().trim().length() > 4 && 
            new String(jpsfSenha.getPassword()).trim().length() > 4){

            Funcionario f = new Funcionario();
            f.setNome(txfNome.getText().trim());            
            f.setSenha(new String(jpsfSenha.getPassword()).trim());
            f.setCpf(txfCPF.getText().trim());
                        
            if(funcionario != null)
                f.setData_cadastro(funcionario.getData_cadastro());
            
            if(funcionario != null)
                f.setData_nascimento(funcionario.getData_nascimento());
            
            
            return f;
         }

         return null;
    }
    
    public void setFuncionarioFormulario(Funcionario f){

        if(f == null){//se o parametro estiver nullo, limpa o formulario
            txfNome.setText("");
            jpsfSenha.setText("");
            txfCPF.setText("");
            txfDataCadastro.setText("");
            txfDataNascimento.setText("");
            txfNome.setEditable(true);
            funcionario = null;

        }else{

            funcionario = f;
            txfNome.setEditable(false);
            txfNome.setText(funcionario.getNome());
            jpsfSenha.setText(funcionario.getSenha());
            txfCPF.setText(funcionario.getCpf());
            txfDataCadastro.setText(format.format(f.getData_cadastro().getTime()));
            if(f.getData_nascimento()!= null)
                txfDataNascimento.setText(format.format(f.getData_nascimento().getTime()));

        }

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpsfSenha;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblDataUltimoLogin;
    private javax.swing.JLabel lblDtCadastro;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JTextField txfCPF;
    private javax.swing.JTextField txfDataCadastro;
    private javax.swing.JTextField txfDataNascimento;
    private javax.swing.JTextField txfNome;
    // End of variables declaration//GEN-END:variables
}
